const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");
const dns = require("dns").promises;

const NGINX_SITES_DIR = "/etc/nginx/sites-available";
const NGINX_ENABLED_DIR = "/etc/nginx/sites-enabled";
const APP_PORT = process.env.PORT || 3000;

/**
 * Check if autoconfig/autodiscover subdomains resolve to our server,
 * then create Nginx vhost and get SSL certs automatically.
 *
 * Call this after DNS verification passes for a domain.
 */
async function provisionAutoconfig(domain) {
  const subdomains = [`autoconfig.${domain}`, `autodiscover.${domain}`];
  const confName = `nodemail-autoconfig-${domain}`;
  const confPath = path.join(NGINX_SITES_DIR, confName);

  // Check if already provisioned
  if (fs.existsSync(confPath)) {
    console.log(`Autoconfig: ${domain} already provisioned`);
    return { success: true, message: "Already configured" };
  }

  // Verify subdomains resolve (don't provision if DNS not ready)
  const resolved = [];
  for (const sub of subdomains) {
    try {
      const addrs = await dns.resolve4(sub);
      if (addrs && addrs.length > 0) {
        resolved.push(sub);
      }
    } catch (_) {
      // Not resolvable yet
    }
  }

  if (resolved.length === 0) {
    return {
      success: false,
      message: `DNS not ready. Add CNAME records for autoconfig.${domain} and autodiscover.${domain} first.`,
    };
  }

  // Check if Nginx is installed
  try {
    execSync("which nginx", { stdio: "pipe" });
  } catch (_) {
    return { success: false, message: "Nginx not installed on this server" };
  }

  // Check if sites-available dir exists
  if (!fs.existsSync(NGINX_SITES_DIR)) {
    return { success: false, message: `${NGINX_SITES_DIR} not found` };
  }

  // Create Nginx vhost
  const serverNames = resolved.join(" ");
  const nginxConf = `# Auto-generated by NodeMail for ${domain}
server {
    listen 80;
    server_name ${serverNames};

    location / {
        proxy_pass http://127.0.0.1:${APP_PORT};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
`;

  try {
    // Write config
    fs.writeFileSync(confPath, nginxConf);
    console.log(`Autoconfig: Created Nginx config at ${confPath}`);

    // Enable site
    const enabledPath = path.join(NGINX_ENABLED_DIR, confName);
    if (!fs.existsSync(enabledPath)) {
      fs.symlinkSync(confPath, enabledPath);
    }

    // Test nginx config
    execSync("nginx -t", { stdio: "pipe" });

    // Reload nginx
    execSync("systemctl reload nginx", { stdio: "pipe" });
    console.log(`Autoconfig: Nginx reloaded for ${serverNames}`);

    // Get SSL cert via Certbot
    try {
      const certDomains = resolved.map(s => `-d ${s}`).join(" ");
      execSync(
        `certbot --nginx ${certDomains} --non-interactive --agree-tos --redirect`,
        { stdio: "pipe", timeout: 60000 }
      );
      console.log(`Autoconfig: SSL cert obtained for ${serverNames}`);
    } catch (certErr) {
      console.error(`Autoconfig: SSL cert failed (HTTP still works):`, certErr.message);
      return {
        success: true,
        message: `Nginx configured for ${resolved.join(", ")}. SSL cert failed — run manually: certbot --nginx ${resolved.map(s => '-d ' + s).join(' ')}`,
        ssl: false,
      };
    }

    return {
      success: true,
      message: `Nginx + SSL configured for ${resolved.join(", ")}`,
      ssl: true,
    };

  } catch (err) {
    // Cleanup on failure
    try { fs.unlinkSync(confPath); } catch (_) {}
    try { fs.unlinkSync(path.join(NGINX_ENABLED_DIR, confName)); } catch (_) {}
    console.error(`Autoconfig: Failed for ${domain}:`, err.message);
    return { success: false, message: `Setup failed: ${err.message}` };
  }
}

/**
 * Remove Nginx config for a domain (call when domain is deleted).
 */
function removeAutoconfig(domain) {
  const confName = `nodemail-autoconfig-${domain}`;
  try {
    const confPath = path.join(NGINX_SITES_DIR, confName);
    const enabledPath = path.join(NGINX_ENABLED_DIR, confName);
    if (fs.existsSync(enabledPath)) fs.unlinkSync(enabledPath);
    if (fs.existsSync(confPath)) fs.unlinkSync(confPath);
    execSync("nginx -t && systemctl reload nginx", { stdio: "pipe" });
    console.log(`Autoconfig: Removed Nginx config for ${domain}`);
  } catch (err) {
    console.error(`Autoconfig: Cleanup failed for ${domain}:`, err.message);
  }
}

module.exports = { provisionAutoconfig, removeAutoconfig };
