#!/bin/bash
#
# setup-dovecot.sh
#
# Configures Dovecot for NodeMail with virtual users.
# Users authenticate with full email address against MongoDB.
# Run as root: bash scripts/setup-dovecot.sh
#

set -e

MAIL_HOSTNAME="${MAIL_HOSTNAME:-mail.analytica247.com}"
VMAIL_DIR="/var/vmail"
NODEMAIL_DIR="$(cd "$(dirname "$0")/.." && pwd)"

echo "=== NodeMail Dovecot Setup ==="
echo "Mail hostname: $MAIL_HOSTNAME"
echo "NodeMail dir:  $NODEMAIL_DIR"
echo "Vmail dir:     $VMAIL_DIR"
echo ""

# Install Dovecot
echo "[1/6] Installing Dovecot..."
apt install -y dovecot-imapd > /dev/null 2>&1
echo "  Done"

# Create vmail user for virtual mailboxes
echo "[2/6] Creating vmail user..."
if ! id vmail > /dev/null 2>&1; then
  groupadd -g 5000 vmail
  useradd -u 5000 -g vmail -s /usr/sbin/nologin -d $VMAIL_DIR -m vmail
  echo "  Created vmail user (uid 5000)"
else
  echo "  vmail user already exists"
fi
mkdir -p $VMAIL_DIR
chown -R vmail:vmail $VMAIL_DIR

# Make auth script executable
chmod +x $NODEMAIL_DIR/scripts/dovecot-auth.js

# Configure Dovecot
echo "[3/6] Configuring Dovecot..."

cat > /etc/dovecot/local.conf << CONF
# NodeMail Dovecot Configuration
# Auto-generated by setup-dovecot.sh

protocols = imap

# SSL
ssl = required
ssl_cert = </etc/letsencrypt/live/$MAIL_HOSTNAME/fullchain.pem
ssl_key = </etc/letsencrypt/live/$MAIL_HOSTNAME/privkey.pem
ssl_min_protocol = TLSv1.2

# Virtual mail storage
mail_location = maildir:$VMAIL_DIR/%d/%n/Maildir
mail_uid = vmail
mail_gid = vmail
first_valid_uid = 5000
last_valid_uid = 5000

# Auth using NodeMail's MongoDB via checkpassword script
passdb {
  driver = checkpassword
  args = $NODEMAIL_DIR/scripts/dovecot-auth.js
}

userdb {
  driver = static
  args = uid=vmail gid=vmail home=$VMAIL_DIR/%d/%n mail=maildir:$VMAIL_DIR/%d/%n/Maildir
}

# Namespace
namespace inbox {
  inbox = yes
  separator = /

  mailbox Drafts {
    auto = subscribe
    special_use = \Drafts
  }
  mailbox Sent {
    auto = subscribe
    special_use = \Sent
  }
  mailbox Trash {
    auto = subscribe
    special_use = \Trash
  }
  mailbox Spam {
    auto = subscribe
    special_use = \Junk
  }
}

# Logging
log_path = /var/log/dovecot.log
auth_verbose = yes
auth_debug = no
CONF

echo "  Config written to /etc/dovecot/local.conf"

# Update sync script for new maildir paths
echo "[4/6] Updating sync script paths..."
# The sync-maildir.js already uses /home/{user}/Maildir — we need to update it
# for the new virtual user structure: /var/vmail/{domain}/{localpart}/Maildir

cat > $NODEMAIL_DIR/scripts/sync-maildir.js << 'SYNCSCRIPT'
#!/usr/bin/env node
//
// sync-maildir.js
//
// Exports emails from MongoDB to Maildir format for Dovecot.
// Virtual user structure: /var/vmail/{domain}/{localpart}/Maildir/
// Run via cron: */2 * * * * cd /root/nodemail && node scripts/sync-maildir.js
//

require("dotenv").config({ path: require("path").join(__dirname, "..", ".env") });
const mongoose = require("mongoose");
const fs = require("fs");
const path = require("path");
const os = require("os");

const Email   = require("../models/Email");
const User    = require("../models/User");
const Mailbox = require("../models/Mailbox");

const VMAIL_DIR = process.env.VMAIL_DIR || "/var/vmail";

const FOLDER_MAP = {
  inbox:  "",
  sent:   ".Sent",
  drafts: ".Drafts",
  trash:  ".Trash",
  spam:   ".Spam",
};

const SYNC_STATE_FILE = path.join(__dirname, "..", ".maildir-sync-state.json");

function loadSyncState() {
  try { return JSON.parse(fs.readFileSync(SYNC_STATE_FILE, "utf8")); }
  catch (_) { return { lastSync: null, syncedIds: [] }; }
}

function saveSyncState(state) {
  fs.writeFileSync(SYNC_STATE_FILE, JSON.stringify(state, null, 2));
}

function ensureMaildir(basePath) {
  for (const sub of ["new", "cur", "tmp"]) {
    fs.mkdirSync(path.join(basePath, sub), { recursive: true });
  }
}

function emailToRfc822(email) {
  const date = new Date(email.date).toUTCString();
  const headers = [
    `From: ${email.fromName ? email.fromName + ' <' + email.from + '>' : email.from}`,
    `To: ${email.to.join(", ")}`,
    email.cc && email.cc.length > 0 ? `Cc: ${email.cc.join(", ")}` : null,
    `Subject: ${email.subject}`,
    `Date: ${date}`,
    `Message-ID: ${email.messageId || '<' + email._id + '@nodemail>'}`,
    email.inReplyTo ? `In-Reply-To: ${email.inReplyTo}` : null,
    `MIME-Version: 1.0`,
  ].filter(Boolean).join("\r\n");

  if (email.htmlBody && email.htmlBody.trim()) {
    const boundary = `----=_Part_${email._id}`;
    return `${headers}\r\nContent-Type: multipart/alternative; boundary="${boundary}"\r\n\r\n--${boundary}\r\nContent-Type: text/plain; charset=utf-8\r\n\r\n${email.textBody || ''}\r\n\r\n--${boundary}\r\nContent-Type: text/html; charset=utf-8\r\n\r\n${email.htmlBody}\r\n\r\n--${boundary}--\r\n`;
  }
  return `${headers}\r\nContent-Type: text/plain; charset=utf-8\r\n\r\n${email.textBody || ''}\r\n`;
}

async function main() {
  await mongoose.connect(process.env.MONGO_URI);

  const state = loadSyncState();
  const syncedSet = new Set(state.syncedIds || []);

  const query = state.lastSync ? { date: { $gte: new Date(state.lastSync) } } : {};
  const emails = await Email.find(query).populate("owner", "email").lean();
  let synced = 0;

  // Get all mailboxes to map users to their mailbox addresses
  const allMailboxes = await Mailbox.find({ active: true }).lean();

  for (const email of emails) {
    const emailId = email._id.toString();
    if (syncedSet.has(emailId)) continue;
    if (!email.owner || !email.owner.email) continue;

    // Find which mailbox address this user receives at
    // Use the "to" field to determine the mailbox, fall back to first assigned mailbox
    const userMailboxes = allMailboxes.filter(mb =>
      mb.assignedUsers && mb.assignedUsers.some(id => id.toString() === email.owner._id.toString())
    );

    let targetEmail = null;

    // Check if any "to" address matches a mailbox this user has
    if (email.to) {
      for (const toAddr of email.to) {
        const matched = userMailboxes.find(mb => mb.address === toAddr.toLowerCase());
        if (matched) { targetEmail = matched.address; break; }
      }
    }

    // Fallback to first assigned mailbox
    if (!targetEmail && userMailboxes.length > 0) {
      targetEmail = userMailboxes[0].address;
    }

    // Fallback to user email
    if (!targetEmail) {
      targetEmail = email.owner.email;
    }

    const [localPart, domain] = targetEmail.split("@");
    if (!domain) continue;

    const folderSuffix = FOLDER_MAP[email.folder] || "";
    const maildirBase = folderSuffix
      ? path.join(VMAIL_DIR, domain, localPart, "Maildir", folderSuffix)
      : path.join(VMAIL_DIR, domain, localPart, "Maildir");

    ensureMaildir(maildirBase);

    const subdir = email.read ? "cur" : "new";
    const filename = `${Date.now()}.${emailId}.${os.hostname()}`;
    const flags = email.read ? ":2,S" : "";
    const filePath = path.join(maildirBase, subdir, filename + flags);

    fs.writeFileSync(filePath, emailToRfc822(email));
    syncedSet.add(emailId);
    synced++;
  }

  // Fix ownership
  if (synced > 0) {
    try {
      const { execSync } = require("child_process");
      execSync(`chown -R vmail:vmail ${VMAIL_DIR}`, { stdio: "pipe" });
    } catch (_) {}
    console.log(`Synced ${synced} emails to Maildir`);
  }

  saveSyncState({
    lastSync: new Date().toISOString(),
    syncedIds: [...syncedSet].slice(-10000),
  });

  await mongoose.disconnect();
}

main().catch((err) => { console.error("Sync error:", err); process.exit(1); });
SYNCSCRIPT

chmod +x $NODEMAIL_DIR/scripts/sync-maildir.js
echo "  Done"

# Restart Dovecot
echo "[5/6] Restarting Dovecot..."
systemctl restart dovecot
systemctl enable dovecot
echo "  Done"

# Verify
echo "[6/6] Verifying..."
if ss -tlnp | grep -q ":993"; then
  echo "  IMAP listening on port 993 ✓"
else
  echo "  WARNING: IMAP not listening on 993"
fi

echo ""
echo "=== Setup Complete ==="
echo ""
echo "Users can now log in to IMAP with their FULL email address:"
echo "  Server:   $MAIL_HOSTNAME"
echo "  Port:     993 (SSL/TLS)"
echo "  Username: user@domain.com (full email)"
echo "  Password: NodeMail password"
echo ""
echo "Set up cron for email sync:"
echo '  */2 * * * * cd /root/nodemail && node scripts/sync-maildir.js >> /var/log/nodemail-sync.log 2>&1'
echo ""
